gov:
  name: radar
  exchanges:
    announce:
      type: fanout
      auto_delete: false
      durable: true
  queues:
    logger:
      binding: gov.radar.announce
      exclusive: true
      durable: true
  messages:
    ufo:
      class_name: UFO
      schema:
        shape: String
        color: string
    rocket:
      schema:
        speed: Integer
        target: [Decimal, Decimal]
    plane:
      schema:
        brand: String
        color: String
