mil:
  name: rocket_center
  exchanges:
    commander:
      type: topic
      durable: true
  queues:
    rocket_shield:
      binding: gov.radar.announce
      auto_delete: false
      durable: true
    rocket_launcher:
      binding: gov.radar.announce
      auto_delete: false
      durable: true
  messages:
    protect:
      schema:
        target: [Decimal, Decimal]
    shed:
